# Generated by Django 4.2.11 on 2024-03-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='voites',
            new_name='votes',
        ),
    ]
